### PR TITLE
Build releases

### PR DESCRIPTION
**Pull request by aljosa**
This PR adds support for macOS builds/releases (Windows support in progress).

Note: the pyinstaller/streamlit builds are extremely fragile

### CODE REVIEW

**Comment by KKJSP** [comment]
@aljosa When this will be merged the h5 files folder will change. And if someone updates streamlit from a current build (it pulls from the master branch) then their h5 files will be in the wrong directory and they won't know how to fix it. Is there a reason that change is required?

I wanted to make some changes to streamlit this week. Most of those changes will be in the `./tasks` folder to enable easier implementation of new assays in the future. I was wondering if this PR is ready to be merged? If it is, can you create a `dev` branch and we can merge it on that (to avoid the issues I mentioned earlier and any other merge conflicts that might arise from my work) and I can work start working on that branch.

We will merge `dev` to `master` once we distribute the new installers to everyone else.

**Comment by aljosa** [comment]
@KKJSP When the Streamlit app is packaged as an Electron app and the DMG is installed into the Applications folder the current h5 folder is no longer user accessible.
While the Windows version is currently just a zipped folder it will also get an installer in future versions and will end up in some system folder which is not meant for user manipulation.
I can update the branch to support both h5 locations for now if that would help.
Maybe an option to select a folder with h5 files would be a better solution?

I've removed the update code in `build/run.py` because it doesn't make sense in the context of Electron based GUI app where Streamlit app is running in the background.
I was assuming that the final product will be the Electron based GUI app and that end users won't install Python/Streamlit to run it.
If this is not the case and end users are directly accessing this repository I'll probably need to customize a few things to support direct usage w/o Electron app.

I currently don't have access to this repository so I can only create PRs.

**Comment by KKJSP** [comment]
Okay. Makes sense. The final installer will be an electron app. The users are currently using the pyinstaller executable I shared with them. That one automatically updates with the latest code on the master branch. Until we are ready to share the electron installer I didn't want to make changes to their current workflow i.e. change the h5 files folder. Does that make sense?

**Comment by aljosa** [comment]
@KKJSP yes, that makes sense. Take a look at PR #8, it should keep the current functionality and enable me to update the `build-releases` branch so it doesn't affect the current workflow.

**Comment by aljosa** [comment]
@astaric I've updated the branch to match the new master

**Review by astaric — APPROVED** [review]

**Pull request merged**
